pipeline {
    agent any
    
    tools {
        gradle 'Gradle 7.5.1' 
        //dockerTool 'Docker 20.10.21' 
     }
   
    stages {
       
        stage('Build') {
            steps {
                 checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Taranator0813/Proyecto_Semilleros.git']])
                script{
                 sh """
                    ls -la
                    cd micro_holamundo
                    ls -la
                    pwd
                    gradle init
                    gradle build
                    """
             
                }
            }
        }

    }
}
