pipeline {
      agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock    
        '''
    }
  }
    tools {
        gradle 'Gradle 7.5.1' 
        //dockerTool 'Docker 20.10.21'
        
     }
   
    stages {
        stage('Build') {
            steps {
                script{
                sh """
                ls -la
                cd micro_holamundo
                ls -la
                pwd
                gradle build
               """
                }
            }
        }
       /* stage('test') {
            steps {
                //sh 'gradle docker'
                echo 'test succesfull'
            }
        }*/
        stage('Build Docker Image') {
            steps {
                sh"""
                cd micro_holamundo
                docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                docker build -t micro_imagen:1.0 .
                docker push $DOCKER_USER/micro_imagen:1.0
                
               """
            
            }
        }
              stage('test') {
            steps {
                script{
                withSonarQubeEnv('Sonar') {    
      sh """
   cd micro_holamundo   
   gradle sonarqube \
  -Dsonar.projectKey=Sonar \
  -Dsonar.host.url=http://10.244.0.17:9000 \
  -Dsonar.login=3670318227e397ae3051173da608edc107531fb4
        """
            }
               }     
          }
        }
        stage('Push Docker Image') {
            steps {
               
                echo 'succesfull'
            }
        }
    }
}
