pipeline {
    agent any
    tools {
        gradle 'Gradle 7.5.1' 
        //dockerTool 'Docker 20.10.21'
        
     }
   
    stages {
        stage('Build') {
            steps {
                script{
                sh """
                ls -la
                cd micro_imagen
                ls -la
                pwd
                gradle build
               """
                }
            }
        }
       /* stage('test') {
            steps {
                //sh 'gradle docker'
                echo 'test succesfull'
            }
        }*/
       /* stage('Build Docker Image') {
            steps {
                sh"""
                cd micro_imagen
                docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                docker build -t micro_imagen:1.0 .
                docker push $DOCKER_USER/micro_imagen:1.0
                
               """
            
            }
        }*/
              stage('test') {
            steps {
                script{
                withSonarQubeEnv('Sonar') {    
      sh """
   cd micro_imagen   
   gradle sonarqube \
  -Dsonar.projectKey=Sonar \
  -Dsonar.host.url=http://10.0.200.102:9000 \
  -Dsonar.login=af6d7d25c0eeecbfc1baf88a0d74aef0c8173810
        """
            }
               }     
          }
        }
        stage('Push Docker Image') {
            steps {
               
                echo 'succesfull'
            }
        }
    }
}
